---
- file: dest=/opt/greetings state=directory mode=0755
- shell: aws s3 cp s3://{{ deploy_bucket }}/deploy/{{ app_binary }} /opt/greetings/{{ app_binary }} 
- shell: java -jar /opt/greetings/{{ app_binary }} & 
